# 配置 redis 相关内容
spring:
  redis:
    # Redis服务器地址
    host: 192.168.3.129
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认位0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 1800000
    password: syning


    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 最大阻塞等待时间（复数表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0




