spring:


  # 开启 HiddenHttpMethodFilter 拦截
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#    type: com.zaxxer.hikari.HikariDataSource       # 默认
# 配置数据源，连接哪个数据库

  datasource:
    url: jdbc:mysql://localhost:3306/tmp
    username: root
    password: syning
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.syning.boot.boot05web03.*   # 监控 SpringBean
      filters: stat,wall   # 底层开启功能，stat(sql 监控)，wall(防火墙监控)

      # 监控 servlet 页配置
      stat-view-servlet:
        enabled: true
        login-username: syning
        login-password: 0310
        restEnable: false

      # 监控 web 页配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      # 对开启功能的详细配置
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false





# 配置 mybatis 规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #configuration:
    #map-underscore-to-camel-case: true    # 开启驼峰命名映射规则，和指定 mybatis-config.xml 只能二选一，要么开启规则，放在配置文件中配置





